language: php

# Build matrix options
matrix:
  include:
      env: WP_TRAVISCI=travis:phpunit
    - php: 7.2
      env: WP_TRAVISCI=travis:phpunit
    - php: hhvm
      env: WP_TRAVISCI=travis:phpunit
 

env:
  - WP_VERSION=master WP_MULTISITE=1