# Main Travis CI configuration file for wordpress-plugin tests
# https://github.com/benbalter/wordpress-plugin-tests

# Tell Travis CI we're using PHP
language: php

# Versions of PHP to test against
php:
  - '7.2'

script: ./build.sh