# Website generator in Jekyll

name: Station Pro - Your Radio Online
title: Your Easy Radio Player - Station Pro
email: marviorocha@marviorocha.com
description: Your Easy Radio Player and Plugin WP for Web and Mobile
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://stationpro.marviorocha.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: stationpro
youtube_username:  stationpro
facebook_username: stationpro
author: Marvio Rocha
author_url: marviorocha.com

production: false
mailchimp-list: https://mus.us13.list-manage.com/subscribe/post?u=4c6278e721e4ae538e1ef5fde&amp;id=923ffebb4a

copyright: © 2020 - Station Pro - Your Live Station Online
 
plugins:
  - jekyll-feed
  - jekyll-admin

disqus:
  shortname: showbizmus

onsiginal:
  appid: 9bfefa27-04d2-4584-b5b2-348bcf3ef41f
 
collections:
  pages:
    output: true
  posts:
    output: true
    sidebar_label: News

 

include: 
  - .htaccess

jekyll_admin:
  hidden_links:
    - pages
    - staticfiles
 




  # Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
